1. 导入numpy库并简写为 np

In [1]:
import numpy as np

2. 打印numpy的版本和配置说明 

In [2]:
print(np.__version__)

1.17.0


In [3]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


3. 创建一个长度为10的空向量 

In [6]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. 如何找到任何一个数组的内存大小？ 

In [28]:
z=np.zeros((10,10))
print(z)
print(z.size)
print("%d bytes" % (z.size*z.itemsize))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
100
800 bytes


5. 如何从命令行得到numpy中add函数的说明文档?

In [15]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None`

6. 创建一个长度为10并且除了第五个值为1的空向量

In [22]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. 创建一个值域范围从10到49的向量

In [25]:
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. 反转一个向量(第一个元素变为最后一个) 

In [26]:
z=np.arange(50)
z=z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


9. 创建一个 3x3 并且值从0到8的矩阵

In [29]:
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引

In [30]:
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


11. 创建一个 3x3 的单位矩阵

In [31]:
z=np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. 创建一个 3x3x3的随机数组

In [32]:
z=np.random.random((3,3,3))
print(z)

[[[0.73420294 0.60106504 0.35378054]
  [0.55210899 0.49670241 0.55570764]
  [0.94085605 0.15805717 0.59460049]]

 [[0.17606457 0.45405824 0.18795377]
  [0.9833576  0.52284712 0.57856559]
  [0.39607358 0.2422822  0.00113858]]

 [[0.70546167 0.44334966 0.46358519]
  [0.51151828 0.05043089 0.81378033]
  [0.05487926 0.82380084 0.76532187]]]


13. 创建一个 10x10 的随机数组并找到它的最大值和最小值

In [36]:
z=np.random.random((10,10))
Zmin,Zmax=z.min(),z.max()
print(Zmin,Zmax)

0.008350959054295393 0.9850782146788359


14. 创建一个长度为30的随机向量并找到它的平均值

In [37]:
z=np.random.random(30)
m=z.mean()
print(m)

0.48437338072285124


15. 创建一个二维数组，其中边界值为1，其余值为0

In [45]:
z=np.ones((10,10))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. 对于一个存在在数组，如何添加一个用0填充的边界?

In [52]:
z=np.ones((5,5))
z=np.pad(z,pad_width=1,mode='constant',constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17. 以下表达式运行的结果分别是什么? 

In [56]:
print(0 * np.nan)

nan


In [58]:
print(np.nan==np.nan)

False


In [59]:
print(np.inf>np.nan)

False


In [60]:
print(np.nan-np.nan)

nan


In [62]:
print(0.3==(3*0.1))

False


18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置(这个获取对角线元素方法不太理解)

In [ ]:
z=np.diag(1+np.arange(4),k=-1)
print(z)



19. 创建一个8x8 的矩阵，并且设置成棋盘样式(这个也没有理解为什么是这样写的)

In [69]:
z=np.zeros((8,8),dtype=int)
z[1::1,::2]=1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [1 1 1 1 1 1 1 1]
 [1 0 1 0 1 0 1 0]
 [1 1 1 1 1 1 1 1]
 [1 0 1 0 1 0 1 0]
 [1 1 1 1 1 1 1 1]
 [1 0 1 0 1 0 1 0]]


20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?(这题也没有理解是什么意思)

In [70]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


21. 用tile函数去创建一个 8x8的棋盘样式矩阵(该函数具体怎么拼接的也不是很清楚)

In [75]:
z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. 对一个5x5的随机矩阵做归一化

In [76]:
z=np.random.random((5,5))
max,min=z.max(),z.min()
z=(z-min)/(max-min)
print(z)

[[0.12220173 0.044475   0.2288036  0.79608066 0.8235527 ]
 [0.01894063 0.31600275 0.         0.16444478 0.63762775]
 [0.64222039 0.49866118 0.16036178 0.0674442  0.85472234]
 [1.         0.97639905 0.42684709 0.95825634 0.77046491]
 [0.66767578 0.14873598 0.95257451 0.75446371 0.8642021 ]]


23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？(这个是啥子意思)

In [78]:
color=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])
color

F:\alreadyInstalledAnacondaSoftware\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？

In [79]:
z=np.dot(np.ones((5,3)),np.ones((3,2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25. 给定一个一维数组，对其在3到8之间的所有元素取反 

In [85]:
z=np.arange(11)
z[(3<z)&(z<=8)]*=-1
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


26. 下面脚本运行后的结果是什么? 

In [86]:
print(sum(range(5),-1))

9


上面这个是什么意思，这个和是怎么求的？

In [88]:
from  numpy import *
print(sum(range(5),-1))

10


27. 考虑一个整数向量Z,下列表达合法的是哪个? 

In [89]:
z=arange(5)
z**z

array([  1,   1,   4,  27, 256], dtype=int32)

上面这个是什么意思也不太清楚

In [91]:
z=np.arange(5)
2 << z >> 2

array([0, 1, 2, 4, 8], dtype=int32)

In [92]:
z=np.arange(5)
z<-z

array([False, False, False, False, False])

In [94]:
z=np.arange(5)
1j*z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [95]:
z=np.arange(5)
z/1/1

array([0., 1., 2., 3., 4.])

In [96]:
z=np.arange(5)
z<z>z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

28. 下列表达式的结果分别是什么?

In [97]:
print(np.array(0)/np.array(0))

nan


F:\alreadyInstalledAnacondaSoftware\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [98]:
print(array(0)//np.array(0))

0


F:\alreadyInstalledAnacondaSoftware\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [99]:
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


29. 如何从零位对浮点数组做舍入 ?(上面这个没理解)

In [100]:
z=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(z)),z))

[ -9. -10.  -7.  -2.   2.  -7.   7.  -4.   5.   3.]


30. 如何找到两个数组中的共同元素? 

In [106]:
z1=np.random.randint(0,10,10)
z2=np.random.randint(0,10,10)
print(np.intersect1d(z1,z2))

[0 9]


31. 如何忽略所有的 numpy 警告(尽管不建议这么做)?

In [107]:
defaults=np.seterr(all="ignore")
z=np.ones(1)/0

_=np.seterr(**defaults)
an equivalent way,with a context manager:
    with np.errstate(divide='ignore')
    z=np.ones(1)/0

SyntaxError: invalid syntax (<ipython-input-107-251b090481f3>, line 5)

32. 下面的表达式是正确的吗?

In [108]:
np.sqrt(-1)==np.emath.sqrt(-1)

F:\alreadyInstalledAnacondaSoftware\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

33. 如何得到昨天，今天，明天的日期? 

In [111]:
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
today=np.datetime64('today','D')
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print("yesterday is "+str(yesterday))
print("today is"+str(today))
print("tomorrow is"+str(tomorrow))

yesterday is 2019-08-05
today is2019-08-06
tomorrow is2019-08-07


34. 如何得到所有与2016年7月对应的日期？

In [3]:
import numpy as np
z=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?

In [5]:
A=np.ones(3)*1
B=np.ones(3)*2
C=np.ones(3)*3
np.add(A,B,out=B)

array([3., 3., 3.])

In [17]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [18]:
np.negative(A,out=A)

array([-0.5, -0.5, -0.5])

In [19]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

36. 用五种不同的方法去提取一个随机数组的整数部分

In [23]:
z=np.random.uniform(0,10,10)
print(z-z%1)
print(z)

[3. 5. 2. 2. 6. 1. 4. 6. 5. 5.]
[3.42365904 5.99392609 2.68122484 2.64232228 6.25564453 1.04877789
 4.43217724 6.57347837 5.76399646 5.5143712 ]


In [24]:
print(np.floor(z))

[3. 5. 2. 2. 6. 1. 4. 6. 5. 5.]


In [25]:
print(np.ceil(z)-1)

[3. 5. 2. 2. 6. 1. 4. 6. 5. 5.]


In [26]:
print(z.astype(int))

[3 5 2 2 6 1 4 6 5 5]


In [27]:
print(np.trunc(z))

[3. 5. 2. 2. 6. 1. 4. 6. 5. 5.]


37. 创建一个5x5的矩阵，其中每行的数值范围从0到4 

In [28]:
z=np.zeros((5,5))
z+=np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38. 通过考虑一个可生成10个整数的函数，来构建一个数组

In [29]:
def generate():
    for x in  range(10):
        yield x
z=np.fromiter(generate(),dtype=float,count=-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 

In [31]:
z=np.linspace(0,1,11,endpoint=False)[1:]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. 创建一个长度为10的随机向量，并将其排序 

In [32]:
z=np.random.random(10)
z.sort()
print(z)

[0.08157955 0.19405735 0.40781339 0.45635841 0.45931687 0.54947812
 0.56691879 0.58480118 0.66195823 0.99661043]


41.对于一个小数组，如何用比 np.sum更快的方式对其求和？

In [35]:
z=np.arange(10)
np.add.reduce(z)

45

42. 对于两个随机数组A和B，检查它们是否相等(

In [40]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
equal=np.allclose(A,B)
print(equal)
equal2=np.array_equal(A,B)
print(equal2)

False
False


43. 创建一个只读数组(read-only) 

In [42]:
z=np.zeros(10)
z.flags.writeable=False
z[0]=1

ValueError: assignment destination is read-only

44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

In [43]:
z=np.random.random((10,2))
x,y=z[:,0],z[:,1]
R=np.sqrt(x**2+y**2)
T=np.arctan2(y,x)
print(R)
print(T)

[0.87194643 0.56700817 0.73750577 0.7244888  1.10233384 1.29234715
 1.19925275 0.75578279 0.64708542 1.28689616]
[1.38420456 1.3782458  1.19899159 0.45174379 0.84610028 0.88455914
 0.7092878  0.93997652 1.49623596 0.72957091]


45. 创建一个长度为10的向量，并将向量中最大值替换为1

In [47]:
z=np.random.random(10)
print(z)
z[z.argmax()]=1
print(z)

[0.04284059 0.22529886 0.96660359 0.39295373 0.22701472 0.92672169
 0.98511841 0.04521961 0.53326259 0.71625179]
[0.04284059 0.22529886 0.96660359 0.39295373 0.22701472 0.92672169
 1.         0.04521961 0.53326259 0.71625179]


46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域

In [49]:
z=np.zeros((5,5),[('x',float),('y',float)])
z['x'],z['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

In [50]:
x=np.arange(8)
y=x+0.5
c=1.0/np.subtract.outer(x,y)
print(np.linalg.det(c))

3638.163637117973


48. 打印每个numpy标量类型的最小值和最大值？ 

In [51]:
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


49. 如何打印一个数组中的所有数值? 

In [52]:
np.set_printoptions(threshold=np.nan)
z=np.zeros((16,16))
print(z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

50. 给定标量时，如何找到数组中最接近标量的值？

In [53]:
z=np.arange(100)
v=np.random.uniform(0,100)
index=(np.abs(z-v)).argmin()
print(z[index])

40
